### ISSUE TITLE
Changing icons doesn’t work 

### ISSUE THREAD

**Issue by Ketarmin** [khcrysalis/Feather#118]
https://github.com/user-attachments/assets/ff83fe26-97bd-4ab1-96a0-2e5510d6a3e2

**Comment by AushevAhmad** [comment]
If you sideloaded Feather using cert you won't be able to change its icon.. I actually don't know why samara added an ability to change Feathers icon if most users are going to use their certs to sideload it which will make changing icon not possible.. @khcrysalis Have you considered removing an ability to change Feathers icon? Because like I said earlier.. you simply can't change it if you've sideloaded the app using cert...

**Comment by Ketarmin** [comment]
> If you sideloaded Feather using cert you won't be able to change its icon.. I actually don't know why samara added an ability to change Feathers icon if most users are going to use their certs to sideload it which will make changing icon not possible.. @khcrysalis Have you considered removing an ability to change Feathers icon? Because like I said earlier.. you simply can't change it if you've sideloaded the app using cert...

Ahh okay
