### ISSUE TITLE
Add button when signing to toggle on/off PPQprotections

### ISSUE THREAD

**Issue by luniz7** [khcrysalis/Feather#141]
I would like to see a button when I sign an app where I can either turn on PPQ protection or off for that app.  Saves a step from having to go into the settings screen to toggle it on or off before signing an app. Small beans but would be nice.

**Comment by khcrysalis** [comment]
Unlikely I would add ppqcheck protections directly in the signing view, however I'll consider it

**Comment by castdrian** [comment]
I got a go from samara about adding a setting for essentially "dynamic" protection, so if that is enabled feather will attempt to check the itunes search api for the bundle id and only apply the random string if the app exists on the app store, that probably resolves your issue, since I'm guessing your goal is to not change the bundle id of oss/third party apps you install
