### ISSUE TITLE
incorrect CFBundleVersion replacement with CFBundleShortVersionString during app signing

### ISSUE THREAD

**Issue by cooldanya** [khcrysalis/Feather#142]
hi, i encountered an issue where during the app signing process, the CFBundleVersion in Info.plist is replaced by the value of CFBundleShortVersionString. i understand that this 'feature' is partially related to zsign, but still.

i think it might be enough to ensure that the condition in https://github.com/khcrysalis/Feather/blob/c041682452b50c628148958b408d9a6c0eb918f0/Shared/Signing/zsign/bundle.cpp#L567 is not met, meaning we can pass an empty string here https://github.com/khcrysalis/Feather/blob/c041682452b50c628148958b408d9a6c0eb918f0/iOS/Views/Apps/Signing/AppSigningViewController.swift#L171 if it matches the original value.

similarly, i believe the same logic applies to the condition regarding CFBundleName/CFBundleDisplayName.

alternatively, there could be some modification to zsign. 

thanks ❤️

**Comment by khcrysalis** [comment]
Fixed in https://github.com/khcrysalis/Feather/commit/9a6c604aeeece5b00285971c6023fd4fbe97c147, will be available next release.

The reason why it replaces is because every time zsign is executed it's being fed a name and bundleidentifier, this commit changes that where if you haven't modified it then it will just feed zsign with nothing. So, it will ignore the process of changing the info.plist keys.
