### ISSUE TITLE
Handle Updates

### ISSUE THREAD

**Issue by mannyd209** [khcrysalis/Feather#166]
Can we possibly get a feature in the future that will show if the apps we have signed/installed have an update available including the Feather App itself? Also I would like to be able to update the Feather App within itself. Currently it crashes and says it was unable to install the Feather app when I try to install the new updated version. Thanks

**Comment by castdrian** [comment]
the altsource spec provides timestamps and versions but the app has no actual access to the apps installed onto your device so if they attempt something like that it would end up being guesswork trying to determine update prompts (except for feather itself), as for the app installing itself, afaik there's not really a technically feasible way to do that, you'll always have to sideload it via other means to succeed the install

**Comment by khcrysalis** [comment]
As castdrian mentioned yes it is difficult to really determine if an app needs an update. For example, many *piracy* repos reuse the same bundleIdentifier for hundreds of applications which make it extremely difficult to differenciate between apps. 

As for in-app updating, the only feasable way of doing this is to require an external server with zsign to sign with your certificates. So the app can be fed to your device through a server instead of locally (locally would cause a crash, as you would be streaming the IPA to iOS.. while iOS is attempting to update at the same time)

**Comment by khcrysalis** [comment]
Though, I will keep this feature in mind in the future.

**Comment by castdrian** [comment]
I think a good PoC for this would be something along the lines of:

- explicitly save latest successfull install to userdefaults
```swift
struct LatestFeatherInstalledAppVersion {
    let appRepository: String
    let bundleID: String
    let version: String
}
```

- use [background app refresh](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app) to check repo changes for installed apps
- [dispatch background push notification](https://developer.apple.com/documentation/usernotifications/pushing-background-updates-to-your-app) with [an option](https://developer.apple.com/documentation/usernotifications/declaring-your-actionable-notification-types) to perform the update
