### ISSUE TITLE
Can't install apps: "Navigation failed because the request was for an HTTP URL with HTTPS-Only enabled."

### ISSUE THREAD

**Issue by kitsah** [khcrysalis/Feather#210]
This is when using online install method on Wi-Fi.

![image](https://github.com/user-attachments/assets/a893c720-802f-4547-b947-d2974d0a0e5f)

**Comment by GottaLoveAng** [comment]
https requires ssl certs. you cant connect to a local ip with https. you need to turn off https only mode. on another note, feather isnt able to install apps as of now, wait until the next update to try installing things.

**Comment by kitsah** [comment]
> https requires ssl certs. you cant connect to a local ip with https. you need to turn off https only mode. on another note, feather isnt able to install apps as of now, wait until the next update to try installing things.

I understand, how do I disable HTTPS only mode?
Also, sure thing I will wait for the next update.

**Comment by GottaLoveAng** [comment]
i'm not entirely sure how you disable https only mode. i dont think it gets enabled unless you go out of your way to enable it. either that, or it's an extension thats causing it. i've done searching online and i couldnt personally find anything besides extensions.

**Comment by kitsah** [comment]
> i'm not entirely sure how you disable https only mode. i dont think it gets enabled unless you go out of your way to enable it. either that, or it's an extension thats causing it. i've done searching online and i couldnt personally find anything besides extensions.

Hi, sorry to revive this closed issue, however I've really been struggling with this issue and I was hoping someone could help me out. Not sure if feather issue or something, but any assistance for this would be appreciated! For reference, I've tried deleting all Safari extensions and VPNs, but this issue still persists.

Thanks

**Comment by celenityy** [comment]
This should be re-opened @castdrian 

This is likely a one line fix - I’m fairly certain all Feather needs to do is *try* loading the local IP with `https` first *(Ex. `https://192.168.1.78` instead of `http://192.168.1.78`)*. This should give users with `Not Secure Connection Warning` enabled a prompt to proceed with unencrypted `HTTP` - and for users *without* `Not Secure Connection Warning` enabled, Safari should simply automatically fallback to `HTTP` and proceed as usual.
