### ISSUE TITLE
Couple of features

### ISSUE THREAD

**Issue by TomerGamerTV** [khcrysalis/Feather#25]
Hello, I have a couple of ideas that you could try implementing to the app / changing:

1.  Add a progress bar when signing apps/installing them, and add the option to show a log screen like in esign or cydia
2.  Add the ability to switch languages in the app without going to the settings
3.  Add the option to automatically start installing the app after it has been signed
4.  Add the ability to change compression levels for installing apps
5. Separate installed and signed/imported/downloaded apps into different tabs?
6. Background signing/installing? or push a notification to let the user know he needs to reopen the app for it to keep installing
7. Separate download tab to show progress (and show progress on the app thingy)
8. Create a new format for repos so we can open it like in Sileo and view descriptions, screenshots, sizes, versions, etc.
9. Create a sources library for people to search for community repos
10. Repo caching and background refreshing (while using the app) to make it load faster?
11. Is it possible to put a zero-width space in the app identifier?
12. Make it so that when i click on an app in my library it opens a pull menu where i can see both the app details and buttons below to install, resign, etc.
13. Auto certificate import/sharing? Like, make a file format where I can easily share my certificate and import it with one file like in esign.
14. Automatic background refresh of the local certificate
15. Add text below the reset button that states what it resets (Like what does it reset exactly? There are barely any options to reset)
16. Add the ability to mass import repos
17. Add the option to view the logs (in the app and a log file in the files)
18. On the iPhone when changing the tint color it is not obvious to the user that he needs to swipe to the right to see more colors, i need a better solution would be to turn this into a grid where you scroll down to see more, and if you ever add so many colors that the person needs to scroll down make it so the boxes popup a little at the bottom so the user knows there is more below.
19. Why is there an option to change the app icon if it's not working? (Maybe it works with trollstore but normally signing doesn't let me change it... unless it's currently broken?)

Sorry for the massive yap 😂
Might add more later 😝

**Comment by khcrysalis** [comment]
> Add a progress bar when signing apps/installing them

Hard to do, not really necessary.

> add the option to show a log screen like in esign or cydia

Maybe.

> Add the ability to switch languages in the app without going to the settings

Planned already, though there's no localizations yet :)

> Add the option to automatically start installing the app after it has been signed

Seems a bit unneccessary, you should be able to press a few more buttons to install.

> Add the ability to change compression levels for installing apps

ZIPFoundation doesn't support this, and compressing apps is really only used when sharing. Not doing.

> Separate installed and signed/imported/downloaded apps into different tabs?

Unneccessary, I've done this by design.

> Background signing/installing? or push a notification to let the user know he needs to reopen the app for it to keep installing

It's better for you to wait.

> Separate download tab to show progress (and show progress on the app thingy)

Not doing this, you should watch the progress with the progress circle.

> Create a new format for repos so we can open it like in Sileo and view descriptions, screenshots, sizes, versions, etc.

Unneccessary.

> Create a sources library for people to search for community repos

Unneccessary.

> Repo caching and background refreshing (while using the app) to make it load faster?

Unneccessary.

> Is it possible to put a zero-width space in the app identifier?

Stop doing stuff that may not work.

> Make it so that when i click on an app in my library it opens a pull menu where i can see both the app details and buttons below to install, resign, etc.

Unneccessary.

> Auto certificate import/sharing? Like, make a file format where I can easily share my certificate and import it with one file like in esign.

Unneccessary.

> Automatic background refresh of the local certificate

You can manually press the button yourself.

> Add text below the reset button that states what it resets (Like what does it reset exactly? There are barely any options to reset)

It resets network cache, such as images.

> Add the ability to mass import repos

Planned.

> Add the option to view the logs (in the app and a log file in the files)

Planned.

> On the iPhone when changing the tint color it is not obvious to the user that he needs to swipe to the right to see more colors, i need a better solution would be to turn this into a grid where you scroll down to see more, and if you ever add so many colors that the person needs to scroll down make it so the boxes popup a little at the bottom so the user knows there is more below.

Unneccessary, people should learn how to scroll.

> Why is there an option to change the app icon if it's not working? (Maybe it works with trollstore but normally signing doesn't let me change it... unless it's currently broken?)

It's a limitation to certain certificates, works for me!

**Comment by TomerGamerTV** [comment]
> Seems a bit unneccessary, you should be able to press a few more buttons to install.

Isn't every designer's job to make it fewer buttons?? It's just a waste of time having to press multiple buttons to achieve one thing.

> It's better for you to wait.

The app breaks if the user accidentally exists the app and the app can't fix itself, only if i force close it.
> Not doing this, you should watch the progress with the progress circle.

Bad decision, not only does the circle doesn't show any progress, it can also be easily lost when searching for other stuff and for some weird reason I've seen the progress circle on apps i didn't even download.

> Create a sources library for people to search for community repos
 Unneccessary.

I bet if you made a poll people would have voted yes, It would make searching for repos way easier.

>Add text below the reset button that states what it resets (Like what does it reset exactly? There are barely any options to reset)
It resets network cache, such as images.

Who would have guessed it resets network cache?? usually reset buttons reset settings, you should add a note below saying what it does because a random reset button with no description is bad UI design.

> Unneccessary, people should learn how to scroll.

Also bad decision, how are they supposed to figure out they can scroll to the side if there is no indication that it's even possible?? Stuff like this is bad, even apple in their photos app had to change how something works because it wasn't intuitive.

> It's a limitation to certain certificates, works for me!

Are you the only person using the certificate? How did you sign the original app? Did you enable anything special on their website?

**Comment by khcrysalis** [comment]
> Bad decision, not only does the circle doesn't show any progress, it can also be easily lost when searching for other stuff and for some weird reason I've seen the progress circle on apps i didn't even download.

"not only does the circle doesn't show any progress", it does, and no, it cannot be easily lost because I've made a system to prevent that from happening by constantly checking in the background of the app when you're navigating.

If theres an issue, please make a pull request.

> Isn't every designer's job to make it fewer buttons?? It's just a waste of time having to press multiple buttons to achieve one thing. 

I've thought about it before, really, however I thought it would be better for people to get used to managing applications.

> The app breaks if the user accidentally exists the app and the app can't fix itself, only if i force close it.

It's designed for you to wait.

> I bet if you made a poll people would have voted yes, It would make searching for repos way easier.

A poll won't change my decision on how I manage repositories, and I want to avoid promotion of any piracy in feather, which most altstore repos seem to provide it seems. At least, the ones not featured in altstores documentation.

> Who would have guessed it resets network cache?? usually reset buttons reset settings, you should add a note below saying what it does because a random reset button with no description is bad UI design.

What? I've provided a reset category for those wanting to reset certain parts of the app, and I chose for now to only include resetting of network cache. Pressing on it will give a clear indicator on what it would clear and remove. Stop acting like I haven't already since it could've been figured out in an instant.

> Also bad decision, how are they supposed to figure out they can scroll to the side if there is no indication that it's even possible?? Stuff like this is bad, even apple in their photos app had to change how something works because it wasn't intuitive.

I'm sorry, but, shouldn't be that hard to figure it out for such a niche customizability option :) 

> Are you the only person using the certificate? How did you sign the original app? Did you enable anything special on their website?

This is a common thing amongst people using certificates from paid signing services, it recently broke, for the ones who are able to change the icon such as the people using alternative methods, sure its there.

## Conclusion

Feather is really it's own thing, I would rather not go to the boring aproach of implementing stuff like the download tab just because esign has it etc. Rather, do stuff that really no one has done before such as making the user press on the download button and have it animate in front of them.

Most of your feature requests are niche and really not worth implementing because they only fit your specific standards, feather is a stand alone project really meant for me though I do accept feedback to make it better. Making it exactly like ESign is really... not one of them. Sure I wanted an alternative, but not an exact replica.

**Comment by khcrysalis** [comment]
So understand a lot of these features you've requested won't be added, I've done a lot of planning out for this app already! And again, this app is an alternative, NOT an exact replica of an existing app.

I'll be making a roadmap soon of many requested features that actually need to be implemented, would be in an issue similar to yours.

**Comment by khcrysalis** [comment]
Added some features from here already in this release https://github.com/khcrysalis/Feather/releases/tag/v1.0.1
