### ISSUE TITLE
Importing an IPA with a version number that is the same to an already imported app makes the process hang

### ISSUE THREAD

**Issue by Spritzerland** [khcrysalis/Feather#50]
for example, i import foo.ipa with the version being 6.9 first. when i try to import bar.ipa with the version being 6.9 also, it hangs the importing process & doesn't import fully (it creates the folders with everything inside it afaik but doesn't import it in the app)

**Comment by khcrysalis** [comment]
> Importing an IPA with a version number that is the same to an already imported app makes the process hang

I would need some proof to this, because there is no instance in the code where a version number effects importing. As importing is only based on what CoreData accepts and not the direct contents of the Info.plist.

Every imported app gets their own directory, this is to avoid any conflicts for those wanting to download multiple of the same versions.

**Comment by Spritzerland** [comment]
hmm, seems to be an issue on my part. it just didn't want to import the app for me. strange. ill get out of your hair
